import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { SidebarNavigation } from "@/components/SidebarNavigation";
import { getCollections } from "@/actions/collections";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const collectionsResult = await getCollections();
  const collections = collectionsResult.success ? collectionsResult.data : [];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <SidebarNavigation collections={collections} />

          <div className="w-full min-h-screen flex flex-col">
            <SidebarTrigger />
            <div className="py-4 px-8 flex-1">{children}</div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
